export const skillsList = [
  "Accounting",
  "Active Listening",
  "Adaptability",
  "Advising",
  "Agile Methodologies",
  "Analytical Thinking",
  "AngularJS",
  "Attention Management",
  "Attention to Detail",
  "AutoCAD",
  "Brand Management",
  "Budget Management",
  "Business Development",
  "C++",
  "Change Management",
  "Client Management",
  "Coaching",
  "Coding",
  "Collaboration",
  "Communication",
  "Conflict Resolution",
  "Content Management",
  "Content Marketing",
  "Creative Problem Solving",
  "Creativity",
  "Critical Thinking",
  "CRM (Customer Relationship Management)",
  "CSS",
  "Customer Service",
  "Data Analysis",
  "Database Management",
  "Decision Making",
  "Dependability",
  "Detail-Oriented",
  "Digital Marketing",
  "Digital Media",
  "Docker",
  "Empathy",
  "Emotional Intelligence",
  "Event Planning",
  "Financial Analysis",
  "Financial Planning",
  "Flexibility",
  "Forecasting",
  "Foreign Languages",
  "Graphic Design",
  "HTML",
  "Illustrator",
  "InDesign",
  "Innovation",
  "Interpersonal Skills",
  "Java",
  "JavaScript",
  "Kotlin",
  "Leadership",
  "Leadership Development",
  "Learning Agility",
  "Management",
  "Market Research",
  "Marketing Strategy",
  "MATLAB",
  "Mentoring",
  "Microsoft Azure",
  "Microsoft Excel",
  "Microsoft Office Suite",
  "Microsoft PowerPoint",
  "Microsoft Word",
  "MongoDB",
  "Multitasking",
  "Negotiation",
  "Networking",
  "Node.js",
  "Organizational Development",
  "Organizational Skills",
  "Patience",
  "Performance Management",
  "Photoshop",
  "PHP",
  "PostgreSQL",
  "Presentation Skills",
  "Problem Solving",
  "Product Management",
  "Programming Languages (e.g., Python, Java)",
  "Project Management",
  "Public Relations",
  "Public Speaking",
  "Python",
  "QuickBooks",
  "React.js",
  "Remote Collaboration",
  "Research",
  "Resilience",
  "Risk Management",
  "Ruby",
  "Sales",
  "Salesforce",
  "Search Engine Optimization (SEO)",
  "Self-Discipline",
  "Self-Motivation",
  "SEO Management",
  "Social Media Management",
  "Social Media Marketing",
  "Software Development",
  "SQL",
  "Statistical Analysis",
  "Strategic Planning",
  "Supply Chain Management",
  "Swift",
  "Tableau",
  "Team Building",
  "Teamwork",
  "Technical Support",
  "Technical Writing",
  "TensorFlow",
  "Time Management",
  "Troubleshooting",
  "UI/UX Design",
  "Unity",
  "Unreal Engine",
  "User Experience (UX) Design",
  "Verbal Communication",
  "Visual Design",
  "Web Development",
  "WordPress",
  "Stress Management",
  "Training",
  "Counseling",
];
